# Generated by Django 5.2.4 on 2026-02-16 17:37

import django.core.validators
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.'), products.validators.validate_image_size]),
        ),
    ]
