# Generated by Django 5.2.4 on 2026-02-20 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcategory_product_category_and_featured'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_acti_2fee29_idx',
            old_name='products_pro_is_acti_153e1a_idx',
        ),
    ]
